{
 "title": "slab",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "slack input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(slack_input_command_total[$interval])",
     "legendFormat": "command"
    },
    {
     "expr": "irate(slack_input_preview_issue_total[$interval])  ",
     "legendFormat": "issue"
    },
    {
     "expr": "irate(slack_input_preview_merge_request_total[$interval])",
     "legendFormat": "merge request"
    },
    {
     "expr": "irate(slack_input_other_total[$interval])",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "gitlab latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(gitlab_request_get_duration_milliseconds_sum[$interval])/rate(gitlab_request_get_duration_milliseconds_count[$interval])",
     "legendFormat": "get"
    }
   ]
  },
  {
   "title": "gitlab request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(gitlab_request_get_duration_milliseconds_count[$interval])",
     "legendFormat": "get"
    }
   ]
  }
 ]
}