#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

mix sentry_recompile
mix run --no-halt
